[project]
name = "microwakeword-python-inference-demo"
version = "0.1.0"
description = "A lightweight wake word detection demo using TensorFlow Lite"
readme = "README.md"
requires-python = ">=3.8,<3.13"
license = { text = "MIT" }
dependencies = [
    "tensorflow>=2.18.0",
    "numpy>=2.0.2"
]
