#!/usr/bin/env bash

# Store the current directory
CURRENT_DIR="$(pwd)"

# Change to root directory
cd "$(dirname "$0")/.."

# Run bootstrap in subshell
python3 script/bootstrap.py

# Activate the virtual environment
if [ -f .venv/bin/activate ]; then  # Linux and macOS
    source .venv/bin/activate
elif [ -f .venv/Scripts/activate ]; then  # Windows
    source .venv/Scripts/activate
else
    echo "Error: Could not find the virtual environment activation script."
    exit 1
fi

# Return to original directory
cd "$CURRENT_DIR"
